// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcxTp4msuvjwvuYVkMtDK-GDfPTLa2bnw',
    appId: '1:1061806108476:web:41b93045032d9979d03839',
    messagingSenderId: '1061806108476',
    projectId: 'recipes-app-6ca52',
    authDomain: 'recipes-app-6ca52.firebaseapp.com',
    storageBucket: 'recipes-app-6ca52.firebasestorage.app',
    measurementId: 'G-MBC5Q78CT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ZiegriskE7ocR1IqDoynXnPZoO4GqJk',
    appId: '1:1061806108476:android:b5dddf2efdbd1a7bd03839',
    messagingSenderId: '1061806108476',
    projectId: 'recipes-app-6ca52',
    storageBucket: 'recipes-app-6ca52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAXdn4O1D2UGPjkP8Uury6yDufjLw9w34',
    appId: '1:1061806108476:ios:c911bb0161a1f380d03839',
    messagingSenderId: '1061806108476',
    projectId: 'recipes-app-6ca52',
    storageBucket: 'recipes-app-6ca52.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAXdn4O1D2UGPjkP8Uury6yDufjLw9w34',
    appId: '1:1061806108476:ios:c911bb0161a1f380d03839',
    messagingSenderId: '1061806108476',
    projectId: 'recipes-app-6ca52',
    storageBucket: 'recipes-app-6ca52.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcxTp4msuvjwvuYVkMtDK-GDfPTLa2bnw',
    appId: '1:1061806108476:web:34f03e4f83216015d03839',
    messagingSenderId: '1061806108476',
    projectId: 'recipes-app-6ca52',
    authDomain: 'recipes-app-6ca52.firebaseapp.com',
    storageBucket: 'recipes-app-6ca52.firebasestorage.app',
    measurementId: 'G-HM8JHZQHVN',
  );
}
